title: erpin.club Status Page
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.erpin.club
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 2006-01-02 15:04
  down: "#e60000"
  systems:
    - name: mainpage
      category: Uncategorized
    - name: blog
      description: ""
      category: Uncategorized
    - name: canvaswiki
      category: Uncategorized
    - name: git
      category: Uncategorized
    - name: mail
      category: Uncategorized
    - name: mc (ramvi-land)
      category: Uncategorized
  dateFormat: 2006-01-02 15:04 (UTC)
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/403.webp
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      closed: true
      untitled: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
